# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20171119_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
