# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_location_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
