# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_airline_route_routeavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.Airline'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_routes', to='routes.Location'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='routes.Location'),
        ),
        migrations.AlterField(
            model_name='routeavailability',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.Route'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('origin', 'destination', 'airline')]),
        ),
        migrations.AlterUniqueTogether(
            name='routeavailability',
            unique_together=set([('route', 'day', 'cabin')]),
        ),
    ]
