# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20171119_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('code', 'type')]),
        ),
    ]
