# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20171119_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeavailability',
            name='seats',
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='seats_available_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='seats_available_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='seats_available_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='seats_available_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routeavailability',
            name='miles_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
