# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20171119_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeavailability',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
