# Generated by Django 2.0.1 on 2018-04-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_auto_20171215_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_peak', models.BooleanField()),
                ('day', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='distance_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='is_peak',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='routes.Location'),
        ),
    ]
