# Generated by Django 2.0.1 on 2018-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_auto_20180402_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeavailability',
            name='distance_miles',
        ),
        migrations.RemoveField(
            model_name='routeavailability',
            name='miles_cost',
        ),
        migrations.AddField(
            model_name='route',
            name='distance_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='miles_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='miles_cost_peak',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
