# Generated by Django 2.0.1 on 2018-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20180402_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='miles_cost',
        ),
        migrations.RemoveField(
            model_name='route',
            name='miles_cost_peak',
        ),
        migrations.AddField(
            model_name='routeavailability',
            name='miles_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
